apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  links:
    - title: Env0 Console
      url: ${{ values.environmentUrl }}
  tags:
    - env0
  annotations:
    github.com/project-slug: env0/env0-backstage-plugin
    env0.com/environment-id: ${{ values.id }}
    env0.com/organization-id: ${{ values.organizationId }}
spec:
  type: ${{ values.type }}
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
