apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: The env0 environment ${{ values.id }} deployed under the project ${{ values.projectId }}
  links:
    - title: Env0 Console
      url: ${{ values.environmentUrl }}
  tags:
    - env0
  annotations:
    github.com/project-slug: env0/env0-backstage-plugin
spec:
  type: ${{ values.type }}
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
