apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-env0-environment
  title: Create an env0 Environment
  description: |
    A template for creating an env0 environment.
  tags:
    - env0
spec:
  type: infrastructure
  parameters:
    - title: Basic Information Step
      required:
        - env0_template_id
        - env0_environment_name
        - env0_project_id
      properties:
        env0_template_id:
          title: Template
          type: string
          ui:field: Env0TemplateSelector
          description: Select the env0 template to deploy
        env0_environment_name:
          title: Environment Name
          type: string
          description: Define the new env0 environment name
        env0_deployment_comment:
          title: Deployment Comment
          type: string
          description: Define a comment for the initial env0 deployment
        env0_project_id:
          # TODO: on project id selection ticket
          title: Project
          type: string
          description: Select the project to deploy the env0 environment to
  steps:
    - id: create-env0-environment
      name: Create Env0 Environment
      action: env0:environment:create
      input:
        templateId: ${{ parameters.env0_template_id }}
        projectId: ${{ parameters.env0_project_id }}
        name: ${{ parameters.env0_environment_name }}
        comment: ${{ parameters.env0_deployment_comment }}
        # TODO: pass variables and validate that it works
    - id: template
      name: Render the Backstage template
      action: fetch:template
      input:
        url: ./template
        values:
          id: ${{ steps['create-env0-environment'].output.environmentId }}
          name: ${{ parameters.env0_environment_name }}
          projectId: ${{ parameters.env0_project_id }}
          environmentUrl: ${{ steps['create-env0-environment'].output.environmentUrl }}
          # These are the component's default values, which you can customize with your own
          type: service
          lifecycle: experimental
          owner: default
    - id: register
      name: Register Component to Catalog
      action: catalog:register
      input:
        repoContentsUrl: file://./template
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Open Env0 Environment
        url: "${{ steps['create-env0-environment'].output.environmentUrl }}"
      - title: Open the Backstage Component
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
