apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: env0-environment-from-template
  title: Deploy an env0 Environment
  description: |
    A template to deploy an env0 environment.
    This template will create an env0 environment as a backstage component.
    You will choose an env0 template to be deployed as an env0 environment from an exposed list of env0 templates by your admin.
  tags:
    - env0
spec:
  type: infrastructure
  parameters:
    - title: Basic Information Step
      required:
        - env0_template_id
        - env0_environment_name
      properties:
        env0_template_id:
          title: env0 Template
          type: string
          ui:field: Env0TemplateSelector
          description: IaC template to be deployed.
        env0_environment_name:
          title: Environment Name
          type: string
          description: Give your component a name
        env0_deployment_comment:
          title: Deployment Comment
          type: string
          description: Comment to be shown on your deployment
        env0_project_id:
          title: Project ID
          type: string
          ui:field: Env0ProjectSelector
          ui:options:
            env0TemplateId: "uuid"
          description: Deploy under the selected env0 project. Projects list effected by your env0 Template selection.
    - title: Variables
      required:
        - env0_variables
      properties:
        env0_variables:
          title: Variables
          type: array
          ui:field: Env0VariablesInput
          ui:backstage:
            review:
              show: false
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: string
            additionalProperties: true
          required:
            - env0_variables
          description: IaC / Environment Variables
  steps: # the pipeline deploy steps, using our custom actions
    - id: createEnv0Environment
      name: Create Env0 Environment
      action: env0:environment:create
      input:
        templateId: ${{ parameters.env0_template_id }}
        projectId: ${{ parameters.env0_project_id }}
        name: ${{ parameters.env0_environment_name }}
        comment: ${{ parameters.env0_deployment_comment }}
        variables: ${{ parameters.env0_variables }}
    - id: template
      name: Render the Backstage template
      action: fetch:template
      input:
        url: ./template
        values:
          environmentName: "${{ parameters.env0_environment_name }}"
          environmentDescription: ${{ parameters.deploy_comment }}
          organizationId: ${{parameters.organizationId}}
          environmentId: ${{ steps['deployEnv0Template'].output.environmentId }}
          # owner: ${{ parameters.owner }}
          # system: ${{ parameters.system }}
    - id: registerEnv0Environment
      name: Register Catalog
      action: catalog:register
      input:
        # TODO: make sure rendering catalog-info.yaml works in order to register the entity
        #repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Env0 Environment link
        url: "https://app.env0.com/p/${{ parameters.env0_project_id }}/environments/${{ steps['createEnv0Environment'].output.environmentId }}"
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
