apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-env0-environment
  title: Create an env0 Environment
  description: |
    A template for creating an env0 environment.
  tags:
    - env0
spec:
  type: infrastructure
  parameters:
    - title: Gather Information
      required:
        - env0_template_id
        - env0_environment_name
        - env0_project_id
      properties:
        env0_template_id:
          title: Template
          type: string
          ui:field: Env0TemplateSelector
          description: Select the env0 template to deploy
        env0_environment_name:
          title: Environment Name
          type: string
          description: Define the new env0 environment name
        env0_deployment_comment:
          title: Deployment Comment
          type: string
          description: Leave a comment on the initial env0 deployment
        env0_project_id:
          title: Project
          type: string
          ui:field: Env0ProjectSelector
          description: Select the project to deploy the env0 environment in
    - title: Variables
      required:
        - env0_variables
      properties:
        env0_variables:
          title: Variables
          type: array
          ui:field: Env0VariablesInput
          ui:backstage:
            review:
              show: false
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: string
            additionalProperties: true
          required:
            - env0_variables
          description: IaC / Environment Variables
    - title: Choose a Location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github:
                  - workflow
            allowedHosts:
              - github.com
        branch:
            title: Branch
            type: string
            description: The branch to push the template to
            default: main
  steps:
    - id: create-env0-environment
      name: Create Env0 Environment
      action: env0:environment:create
      input:
        templateId: ${{ parameters.env0_template_id }}
        projectId: ${{ parameters.env0_project_id }}
        name: ${{ parameters.env0_environment_name }}
        comment: ${{ parameters.env0_deployment_comment }}
        variables: ${{ parameters.env0_variables }}
    - id: template
      name: Render the Backstage template
      action: fetch:template
      input:
        url: ./template
        values:
          id: ${{ steps['create-env0-environment'].output.environmentId }}
          name: ${{ parameters.env0_environment_name }}
          projectId: ${{ parameters.env0_project_id }}
          templateId: ${{ parameters.env0_template_id }}
          environmentUrl: ${{ steps['create-env0-environment'].output.environmentUrl }}
          organizationId: ${{ steps['create-env0-environment'].output.organizationId }}
          # These are the component's default values, which you can customize with your own
          type: service
          lifecycle: experimental
          owner: default
    - id: publish
      name: Publish to GitHub
      action: github:repo:push
      input:
        allowedHosts: ["github.com"]
        token: ${{ secrets.USER_OAUTH_TOKEN or false }}
        description: Publish the template of ${{ parameters.env0_environment_name }} to GitHub
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: ${{ parameters.branch }}
        protectDefaultBranch: false
    - id: register
      name: Register Component to Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Open Env0 Environment
        url: "${{ steps['create-env0-environment'].output.environmentUrl }}"
      - title: Open Backstage Component
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
