apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: env0-environment-from-template
  title: Deploy env0 Environment
  description: |
    A template to deploy an env0 environment.
    This template will create an environment as a backstage component.
    You will choose an env0 template to be deployed as an env0 environment.
    Choosing from an exposed list of env0 templates.
  tags:
    - env0
  annotations:
    env0.com/organization-id: '<org-id>' # Set by devops admin
    env0.com/project-id: '<project-id>' # Optional annotation; or fetched by the template selection dynamically
spec:
  type: infrastructure
  parameters:
    - title: Basic Information Step
      required:
        - env0_template_id
        - env0_environment_name
      properties:
        env0_template_id:
          title: env0 Template
          type: string
          #ui:autocomplete: true # Autocomplete field using the backend route
          # Or hardcoded until we implement the autocomplete logic
          enum:
            - 123
            - 321
          enumNames:
            - Terraform EC2
            - Network microservice [Workflow]
          description: IaC template to be deployed.
        env0_environment_name:
          title: Environment Name
          type: string
          description: Give your component a name
        deploy_comment:
          title: First deployment comment
          type: string
          description: comment to be shown on your deployment
    - title: Variables
      required:
        - env0_variables
      properties:
        env0_variables:
          title: Variables
          type: string # we will need to implement a new type of component here
          description: TF / Environment Variables
  steps: # the pipeline deploy steps, using our custom actions
    - id: deployEnv0Template # see custom deploy later in TD
      name: Deploy via env0
      action: env0:environment:create
      input:
        blueprintId: ${{ parameters.env0_template_id }}
        envName: ${{ parameters.env0_environment_name }}
        comment: ${{ parameters.deploy_comment }}
        configurationChanges: ${{ parameters.??? }}
        outputs:
        - environmentId: ${{ steps['deployEnv0Template'].output.env0EnvironmentId }}
    - id: template
      name: Render the Backstage template
      action: fetch:template
      input:
        url: ./template
        values:
          environmentName: "${{ parameters.env0_environment_name }}"
          environmentDescription: ${{ parameters.deploy_comment }}
          organizationId: ${{parameters.organizationId}}
          environmentId: ${{parameters.environmentId}}
#          owner: ${{ parameters.owner }}
#          system: ${{ parameters.system }}
    - id: registerEnv0Environment # see register process later in TD
      name: Register Catalog
      action: catalog:register
      input:
        #repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

