name: PR Auto Labeler
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-labeler:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v5.0.0 # Reads from .github/labeler.yml
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
